# -*- coding: utf-8 -*-
"""Milestone

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xvKEABfyh1UYlZKEmlTKPPiWOAZCtWtJ
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
# %matplotlib inline

data = pd.read_csv('/content/Final_data.csv')
data.head()

data.dtypes

data['Age'].hist(figsize=(5, 5))
plt.xlabel('Age')
plt.ylabel('Count')
plt.title("Age Distribution")

data['Gender'].hist(figsize=(5, 5))
plt.xlabel('Gender')
plt.ylabel('Count')
plt.title("Gender Distribution")

data["Weight (kg)"].hist(figsize=(5, 5))
plt.xlabel('Weight (kg)')
plt.ylabel('Count')
plt.title("Weight Distribution")

data["Height (m)"].hist(figsize=(5, 5))
plt.xlabel('Height (m)')
plt.ylabel('Count')
plt.title("Height Distribution")

sns.relplot(x = "Weight (kg)", y = "Height (m)", data = data, height=4, aspect=1)
plt.xlabel('Weight (kg)')
plt.ylabel('Height (m)')
plt.title("Weight V. Height")

sns.relplot(x = "Session_Duration (hours)", y = "Calories_Burned", data = data,height=4, aspect=1)
plt.xlabel('Session Duration (hours)')
plt.ylabel('Calories Burned')
plt.title("Session Duration V. Calories Burned")